updated the workflows to add the rerun functionality

diff --git a/.github/workflows/build-client-server.yml b/.github/workflows/build-client-server.yml
--- a/.github/workflows/build-client-server.yml
+++ b/.github/workflows/build-client-server.yml
@@ -3,66 +3,130 @@ name: Build Client, Server & Run only Cypress
 on:
   # This workflow can be triggered manually from the GitHub Actions page
   workflow_dispatch:
-    inputs:
-      previous_run_id:
-        description: 'Run id to download the docker image artifact:'
-        required: false
-        type: string
-        default: "0"
 
 jobs:
-  server-build:
-    name: server-build
-    if: inputs.previous_run_id == '0'
-    uses: ./.github/workflows/server-build.yml
-    secrets: inherit
-    with:
-      pr: 0
-      skip-tests: "true"
+  notify:
+    runs-on: ubuntu-latest
+    steps:
+      # This step creates a comment on the PR with a link to this workflow run.
+      - name: Add a comment on the PR with link to workflow run
+        uses: peter-evans/create-or-update-comment@v2
+        with:
+          issue-number: 23073
+          body: |
+            Tests running at: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>.
+            Workflow: `${{ github.workflow }}`.
+            Commit: `${{ github.event.client_payload.slash_command.args.named.sha }}`.
+            PR: 23073.
+            Perf tests will be available at <https://app.appsmith.com/app/performance-infra-dashboard/pr-details-638dd7cd2913ba43778b915e?pr=23073&runId=${{ github.run_id }}_${{github.run_attempt}}>
 
-  client-build:
-    name: client-build
-    if: inputs.previous_run_id == '0'
-    uses: ./.github/workflows/client-build.yml
+  ci-test:
+    name: ci-test
+    uses: ./.github/workflows/ci-test.yml
     secrets: inherit
     with:
-      pr: 0
-      skip-tests: "true"
+      pr: 23073
 
-  rts-build:
-    name: rts-build
-    if: inputs.previous_run_id == '0'
-    uses: ./.github/workflows/rts-build.yml
-    secrets: inherit
-    with:
-      pr: 0
-      
-  build-docker-image:
-    needs: [ client-build, server-build, rts-build ]
-    # Only run if the build step is successful
-    if: success() && inputs.previous_run_id == '0'
-    name: build-docker-image
-    uses: ./.github/workflows/build-docker-image.yml
-    secrets: inherit
-    with:
-      pr: 0
+  ci-test-result:
+    needs: [ ci-test ]
+    # Only run if the ci-test with matrices step is successful
+    if: always()
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - name: Dump the client payload context
+        env:
+          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
+        run: echo "$PAYLOAD_CONTEXT"
 
-  ci-test-limited:
-    needs: [ build-docker-image ]
-    # Only run if the build step is successful
-    if: success() && inputs.previous_run_id == '0'
-    name: ci-test-limited
-    uses: ./.github/workflows/ci-test-limited.yml
-    secrets: inherit
-    with:
-      pr: 0
+      # Deleting the existing dir's if any
+      - name: Delete existing directories
+        if: needs.ci-test.result != 'success'
+        run: |
+          rm -f ~/failed_spec_ci
+          rm -f ~/combined_failed_spec_ci
 
-  ci-test-limited-existing-docker-image:
-    # Only run if the previous run-id is provided
-    if: inputs.previous_run_id != '0'
-    name: ci-test-limited
-    uses: ./.github/workflows/ci-test-limited.yml
-    secrets: inherit
-    with:
-      pr: 0
-      previous-workflow-run-id: ${{ fromJson(github.event.inputs.previous_run_id) }}
+      # Download failed_spec list for all jobs
+      - uses: actions/download-artifact@v3
+        if: needs.ci-test.result != 'success'
+        id: download_ci
+        with:
+          name: failed-spec-ci
+          path: ~/failed_spec_ci
+          
+      # In case for any ci job failure, create combined failed spec
+      - name: "combine all specs for CI"
+        if: needs.ci-test.result != 'success'
+        run: |
+          echo "Debugging: failed specs in ~/failed_spec_ci/failed_spec_ci*"
+          cat ~/failed_spec_ci/failed_spec_ci*
+          cat ~/failed_spec_ci/failed_spec_ci* | sort -u >> ~/combined_failed_spec_ci
+
+      # Force save the CI failed spec list into a cache
+      - name: Store the combined run result for CI
+        if: needs.ci-test.result != 'success'
+        uses: martijnhols/actions-cache/save@v3
+        with:
+          path: |
+            ~/combined_failed_spec_ci
+          key: ${{ github.run_id }}-"ci-test-result"
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
+            
+      # Upload combined failed CI spec list to a file
+      # This is done for debugging.
+      - name: upload combined failed spec
+        if: needs.ci-test.result != 'success'
+        uses: actions/upload-artifact@v3
+        with:
+          name: combined_failed_spec_ci
+          path: ~/combined_failed_spec_ci
+
+      - name: Get Latest flaky Tests
+        shell: bash
+        run: |
+          curl --request POST --url https://yatin-s-workspace-jk8ru5.us-east-1.xata.sh/db/CypressKnownFailures:main/tables/CypressKnownFailuires/query --header 'Authorization: Bearer ${{ secrets.XATA_TOKEN }}' --header 'Content-Type: application/json'|jq -r |grep Spec|cut -d ':' -f 2 2> /dev/null|sed 's/"//g'|sed 's/,//g' >  ~/knownfailures
+
+     # Verify CI test failures against known failures
+      - name: Verify CI test failures against known failures
+        if: needs.ci-test.result != 'success'
+        shell: bash
+        run: |
+          new_failed_spec_env="<ol>$(comm -1 -3 <(sort ~/knownfailures) <(sort -u ~/combined_failed_spec_ci) | sed 's/|cypress|cypress/\n/g' | sed 's/^/<li>/')</ol>"
+          echo "$new_failed_spec_env"
+          echo "new_failed_spec_env<<EOF" >> $GITHUB_ENV
+          echo "$new_failed_spec_env" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+
+      - name: Add a comment on the PR with new CI failures
+        if: needs.ci-test.result != 'success'
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          issue-number: 23073
+          body: |
+            Workflow run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>.
+            Commit: `${{ github.event.client_payload.slash_command.args.named.sha }}`.
+            The following are new failures, please fix them before merging the PR: ${{env.new_failed_spec_env}}
+            To know the list of identified flaky tests - <a href="https://app.appsmith.com/applications/613868bedd7786286ddd4a6a/pages/63ec710e8e503f763651791a" target="_blank">Refer here</a>
+
+      - name: Add a comment on the PR when ci-test is success
+        if: needs.ci-test.result == 'success'
+        uses: peter-evans/create-or-update-comment@v1
+        with:
+          issue-number: 23073
+          body: |
+            Workflow run: <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>.
+            Commit: `${{ github.event.client_payload.slash_command.args.named.sha }}`.
+            All cypress tests have passed 🎉
+          
+      - name: Dump the client payload context
+        env:
+          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
+        run: echo "$PAYLOAD_CONTEXT"
+
+      - name: Check ci-test set status
+        if: needs.ci-test.result != 'success' || needs.perf-test.result != 'success'
+        run: exit 1
+
