Added exit 1

diff --git a/.github/workflows/ci-test-limited-with-count.yml b/.github/workflows/ci-test-limited-with-count.yml
--- a/.github/workflows/ci-test-limited-with-count.yml
+++ b/.github/workflows/ci-test-limited-with-count.yml
@@ -358,7 +358,11 @@ jobs:
             summary_content=$(cat ${{ github.workspace }}/app/client/cy-repeat-summary.txt | tr '\n' ' ')
             echo "summary_content=$summary_content"
             echo "summary_content=$summary_content" >> $GITHUB_OUTPUT
-            
+            # Check if "Total Failed: 0" is present
+            if ! grep -q "Total Failed: 0" cy-repeat-summary.txt; then
+              echo "Tests failed, failing the GitHub Action."
+              exit 1  # Fails the step if tests failed
+            fi
 
       - name: Trim number of cypress log files
         if: failure()
