Update CI_editor.yml

diff --git a/.github/workflows/CI_editor.yml b/.github/workflows/CI_editor.yml
--- a/.github/workflows/CI_editor.yml
+++ b/.github/workflows/CI_editor.yml
@@ -191,127 +191,127 @@ jobs:
        with:
          name: build
          path: app/client/build
-  #    - name: Pull release server docker container and start it locally
-  #      if: github.ref == 'refs/heads/release' || github.event.pull_request.base.ref == 'release' || github.event.pull_request.head.ref == 'release'
-  #      shell: bash
-  #      run: |
-  #         docker run -d --net=host --name appsmith-internal-server -p 8080:8080 \
-  #           --env APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith \
-  #           --env APPSMITH_REDIS_URL=redis://localhost:6379 \
-  #           --env APPSMITH_ENCRYPTION_PASSWORD=password \
-  #           --env APPSMITH_ENCRYPTION_SALT=salt \
-  #           --env APPSMITH_IS_SELF_HOSTED=false \
-  #           --env APPSMITH_CLOUD_SERVICES_BASE_URL=https://release-cs.appsmith.com \
-  #           --env APPSMITH_CLOUD_SERVICES_USERNAME= \
-  #           --env APPSMITH_CLOUD_SERVICES_PASSWORD= \
-  #           ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:release
-  #    - name: Pull release-frozen server docker container and start it locally
-  #      if: github.ref == 'refs/heads/release-frozen' || github.event.pull_request.head.ref == 'release-frozen'
-  #      shell: bash
-  #      run: |
-  #         docker run -d --net=host --name appsmith-internal-server -p 8080:8080 \
-  #           --env APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith \
-  #           --env APPSMITH_REDIS_URL=redis://localhost:6379 \
-  #           --env APPSMITH_ENCRYPTION_PASSWORD=password \
-  #           --env APPSMITH_ENCRYPTION_SALT=salt \
-  #           --env APPSMITH_IS_SELF_HOSTED=false \
-  #           --env APPSMITH_CLOUD_SERVICES_BASE_URL= \
-  #           --env APPSMITH_CLOUD_SERVICES_USERNAME= \
-  #           --env APPSMITH_CLOUD_SERVICES_PASSWORD= \
-  #           ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:release-frozen
-  #    - name: Pull master server docker container and start it locally
-  #      if: github.ref == 'refs/heads/master'
-  #      shell: bash
-  #      run: |
-  #         docker run -d --net=host --name appsmith-internal-server -p 8080:8080 \
-  #           --env APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith \
-  #           --env APPSMITH_REDIS_URL=redis://localhost:6379 \
-  #           --env APPSMITH_ENCRYPTION_PASSWORD=password \
-  #           --env APPSMITH_ENCRYPTION_SALT=salt \
-  #           --env APPSMITH_IS_SELF_HOSTED=false \
-  #           --env APPSMITH_CLOUD_SERVICES_BASE_URL=https://release-cs.appsmith.com \
-  #           --env APPSMITH_CLOUD_SERVICES_USERNAME= \
-  #           --env APPSMITH_CLOUD_SERVICES_PASSWORD= \
-  #           ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:nightly
-  #    - name: Installing Yarn serve
-  #      run: |
-  #         yarn global add serve
-  #         echo "$(yarn global bin)" >> $GITHUB_PATH
-  #    - name: Setting up the cypress tests
-  #      shell: bash
-  #      env:
-  #        APPSMITH_SSL_CERTIFICATE: ${{ secrets.APPSMITH_SSL_CERTIFICATE }}
-  #        APPSMITH_SSL_KEY: ${{ secrets.APPSMITH_SSL_KEY }}
-  #        CYPRESS_URL: ${{ secrets.CYPRESS_URL }}
-  #        CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
-  #        CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
-  #        CYPRESS_TESTUSERNAME1: ${{ secrets.CYPRESS_TESTUSERNAME1 }}
-  #        CYPRESS_TESTPASSWORD1: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
-  #        CYPRESS_TESTUSERNAME2: ${{ secrets.CYPRESS_TESTUSERNAME2 }}
-  #        CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
-  #        APPSMITH_DISABLE_TELEMETRY: true
-  #        APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
-  #        POSTGRES_PASSWORD: postgres
-  #      run: |
-  #         ./cypress/setup-test.sh
-  #    - name: Run the cypress test
-  #      uses: cypress-io/github-action@v2
-  #      env:
-  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
-  #        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
-  #        CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
-  #        CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
-  #        CYPRESS_TESTUSERNAME1: ${{ secrets.CYPRESS_TESTUSERNAME1 }}
-  #        CYPRESS_TESTPASSWORD1: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
-  #        CYPRESS_TESTUSERNAME2: ${{ secrets.CYPRESS_TESTUSERNAME2 }}
-  #        CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
-  #        APPSMITH_DISABLE_TELEMETRY: true
-  #        APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
-  #        COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
-  #      with:
-  #        browser: chrome
-  #        headless: true
-  #        record: true
-  #        install: false
-  #        parallel: true
-  #        group: "Electrons on Github Action"
-  #        spec: "cypress/integration/Smoke_TestSuite/**/*.js"
-  #        working-directory: app/client
-  #        # tag will be either "push" or "pull_request"
-  #        tag: ${{ github.event_name }}
-  #        env: "NODE_ENV=development"
+     - name: Pull release server docker container and start it locally
+       if: github.ref == 'refs/heads/release' || github.event.pull_request.base.ref == 'release' || github.event.pull_request.head.ref == 'release'
+       shell: bash
+       run: |
+          docker run -d --net=host --name appsmith-internal-server -p 8080:8080 \
+            --env APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith \
+            --env APPSMITH_REDIS_URL=redis://localhost:6379 \
+            --env APPSMITH_ENCRYPTION_PASSWORD=password \
+            --env APPSMITH_ENCRYPTION_SALT=salt \
+            --env APPSMITH_IS_SELF_HOSTED=false \
+            --env APPSMITH_CLOUD_SERVICES_BASE_URL=https://release-cs.appsmith.com \
+            --env APPSMITH_CLOUD_SERVICES_USERNAME= \
+            --env APPSMITH_CLOUD_SERVICES_PASSWORD= \
+            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:release
+     - name: Pull release-frozen server docker container and start it locally
+       if: github.ref == 'refs/heads/release-frozen' || github.event.pull_request.head.ref == 'release-frozen'
+       shell: bash
+       run: |
+          docker run -d --net=host --name appsmith-internal-server -p 8080:8080 \
+            --env APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith \
+            --env APPSMITH_REDIS_URL=redis://localhost:6379 \
+            --env APPSMITH_ENCRYPTION_PASSWORD=password \
+            --env APPSMITH_ENCRYPTION_SALT=salt \
+            --env APPSMITH_IS_SELF_HOSTED=false \
+            --env APPSMITH_CLOUD_SERVICES_BASE_URL= \
+            --env APPSMITH_CLOUD_SERVICES_USERNAME= \
+            --env APPSMITH_CLOUD_SERVICES_PASSWORD= \
+            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:release-frozen
+     - name: Pull master server docker container and start it locally
+       if: github.ref == 'refs/heads/master'
+       shell: bash
+       run: |
+          docker run -d --net=host --name appsmith-internal-server -p 8080:8080 \
+            --env APPSMITH_MONGODB_URI=mongodb://localhost:27017/appsmith \
+            --env APPSMITH_REDIS_URL=redis://localhost:6379 \
+            --env APPSMITH_ENCRYPTION_PASSWORD=password \
+            --env APPSMITH_ENCRYPTION_SALT=salt \
+            --env APPSMITH_IS_SELF_HOSTED=false \
+            --env APPSMITH_CLOUD_SERVICES_BASE_URL=https://release-cs.appsmith.com \
+            --env APPSMITH_CLOUD_SERVICES_USERNAME= \
+            --env APPSMITH_CLOUD_SERVICES_PASSWORD= \
+            ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:nightly
+     - name: Installing Yarn serve
+       run: |
+          yarn global add serve
+          echo "$(yarn global bin)" >> $GITHUB_PATH
+     - name: Setting up the cypress tests
+       shell: bash
+       env:
+         APPSMITH_SSL_CERTIFICATE: ${{ secrets.APPSMITH_SSL_CERTIFICATE }}
+         APPSMITH_SSL_KEY: ${{ secrets.APPSMITH_SSL_KEY }}
+         CYPRESS_URL: ${{ secrets.CYPRESS_URL }}
+         CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
+         CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
+         CYPRESS_TESTUSERNAME1: ${{ secrets.CYPRESS_TESTUSERNAME1 }}
+         CYPRESS_TESTPASSWORD1: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
+         CYPRESS_TESTUSERNAME2: ${{ secrets.CYPRESS_TESTUSERNAME2 }}
+         CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
+         APPSMITH_DISABLE_TELEMETRY: true
+         APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
+         POSTGRES_PASSWORD: postgres
+       run: |
+          ./cypress/setup-test.sh
+     - name: Run the cypress test
+       uses: cypress-io/github-action@v2
+       env:
+         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
+         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
+         CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
+         CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
+         CYPRESS_TESTUSERNAME1: ${{ secrets.CYPRESS_TESTUSERNAME1 }}
+         CYPRESS_TESTPASSWORD1: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
+         CYPRESS_TESTUSERNAME2: ${{ secrets.CYPRESS_TESTUSERNAME2 }}
+         CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
+         APPSMITH_DISABLE_TELEMETRY: true
+         APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
+         COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
+       with:
+         browser: chrome
+         headless: true
+         record: true
+         install: false
+         parallel: true
+         group: "Electrons on Github Action"
+         spec: "cypress/integration/Smoke_TestSuite/**/*.js"
+         working-directory: app/client
+         # tag will be either "push" or "pull_request"
+         tag: ${{ github.event_name }}
+         env: "NODE_ENV=development"
 
-  #     # Upload the screenshots as artifacts if there's a failure
-  #    - uses: actions/upload-artifact@v1
-  #      if: failure()
-  #      with:
-  #        name: cypress-screenshots-${{ matrix.job }}
-  #        path: app/client/cypress/screenshots/
+      # Upload the screenshots as artifacts if there's a failure
+     - uses: actions/upload-artifact@v1
+       if: failure()
+       with:
+         name: cypress-screenshots-${{ matrix.job }}
+         path: app/client/cypress/screenshots/
 
-  # ui-test-result:
-  #   needs: ui-test
-  #   # Only run if the ui-test with matrices step is successful
-  #   if: always()
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   steps:
-  #     - run: echo "All ui-test matrices completed"
+  ui-test-result:
+    needs: ui-test
+    # Only run if the ui-test with matrices step is successful
+    if: always()
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+      - run: echo "All ui-test matrices completed"
 
-  #     - name: Return status for ui-matrix
-  #       run: |
-  #         if [[ "${{ needs.ui-test.result }}" == "success" ]]; then
-  #           echo "Integration tests completed successfully!";
-  #           exit 0;
-  #         elif [[ "${{ needs.ui-test.result }}" == "skipped" ]]; then
-  #           echo "Integration tests were skipped";
-  #           exit 1;
-  #         else
-  #           echo "Integration tests have failed";
-  #           exit 1;
-  #         fi 
+      - name: Return status for ui-matrix
+        run: |
+          if [[ "${{ needs.ui-test.result }}" == "success" ]]; then
+            echo "Integration tests completed successfully!";
+            exit 0;
+          elif [[ "${{ needs.ui-test.result }}" == "skipped" ]]; then
+            echo "Integration tests were skipped";
+            exit 1;
+          else
+            echo "Integration tests have failed";
+            exit 1;
+          fi 
        
   package:   
     needs: ui-test
