Including re-runs in the client and server build workflows

diff --git a/.github/workflows/client-build.yml b/.github/workflows/client-build.yml
--- a/.github/workflows/client-build.yml
+++ b/.github/workflows/client-build.yml
@@ -4,6 +4,11 @@ on:
   # This line enables manual triggering of this workflow.
   workflow_dispatch:
   workflow_call:
+    inputs:
+      pr:
+        description: "This is the PR number in case the workflow is being called in a pull request"
+        required: false
+        type: number
 
   push:
     branches: [release, master]
@@ -37,34 +42,64 @@ jobs:
         shell: bash
 
     steps:
-      # Checkout the code
-      - name: Checkout the merged commit from PR and base branch
-        if: github.event_name == 'pull_request'
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-          ref: refs/pull/${{ github.event.pull_request.number }}/merge
-
-      - name: Checkout the head commit of the branch
-        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
-        uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-
       - name: Figure out the PR number
         run: echo ${{ github.event.pull_request.number }}
 
+      # Check out merge commit with the base branch in case this workflow is invoked via pull request
+      - name: Checkout the merged commit from PR and base branch
+        if: inputs.pr != 0
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+          ref: refs/pull/${{ inputs.pr }}/merge
+
+      # Checkout the code in the current branch in case the workflow is called because of a branch push event
+      - name: Checkout the head commit of the branch
+        if: inputs.pr == 0
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      # Timestamp will be used to create cache key
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +'%Y-%m-%dT%H:%M:%S')"
+
+      # In case this is second attempt try restoring status of the prior attempt from cache
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-
+
+      # Fetch prior run result
+      - name: Get the previous run result
+        id: run_result
+        run: cat ~/run_result 2>/dev/null || echo 'default'
+
+      # Incase of prior failure run the job
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
+
+      # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
+
       - name: Use Node.js 16.14.0
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/setup-node@v1
         with:
           node-version: "16.14.0"
 
       - name: Get yarn cache directory path
+        if: steps.run_result.outputs.run_result != 'success'
         id: yarn-dep-cache-dir-path
         run: echo "::set-output name=dir::$(yarn cache dir)"
 
       # Retrieve npm dependencies from cache. After a successful run, these dependencies are cached again
       - name: Cache npm dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         id: yarn-dep-cache
         uses: actions/cache@v2
         env:
@@ -78,9 +113,11 @@ jobs:
 
       # Install all the dependencies
       - name: Install dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         run: yarn install --frozen-lockfile
 
       - name: Set the build environment based on the branch
+        if: steps.run_result.outputs.run_result != 'success'
         id: vars
         run: |
           echo "::set-output name=REACT_APP_ENVIRONMENT::DEVELOPMENT"
@@ -98,8 +135,9 @@ jobs:
           echo "next_version = $next_version"
           echo ::set-output name=version::$next_version-SNAPSHOT
 
+      # Run the Jest tests only if the workflow has been invoked in a PR and the previous re-run has failed
       - name: Run the jest tests
-        if: github.event_name == 'pull_request'
+        if: steps.run_result.outputs.run_result != 'success' && inputs.pr != 0
         run: REACT_APP_ENVIRONMENT=${{steps.vars.outputs.REACT_APP_ENVIRONMENT}} yarn run test:unit
 
       # We burn React environment & the Segment analytics key into the build itself.
@@ -115,9 +153,22 @@ jobs:
             REACT_APP_VERSION_EDITION="Community" \
             yarn build
 
+      # Restore the previous built bundle if present. If not push the newly built into the cache
+      - name: Restore the previous bundle
+        uses: actions/cache@v2
+        with:
+          path: |
+            app/client/build/
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
+
       # Upload the build artifact so that it can be used by the test & deploy job in the workflow
       - name: Upload react build bundle
         uses: actions/upload-artifact@v2
         with:
           name: build
           path: app/client/build/
+
+      # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
diff --git a/.github/workflows/server-build.yml b/.github/workflows/server-build.yml
--- a/.github/workflows/server-build.yml
+++ b/.github/workflows/server-build.yml
@@ -5,6 +5,11 @@ on:
   # This line enables manual triggering of this workflow.
   workflow_dispatch:
   workflow_call:
+    inputs:
+      pr:
+        description: "This is the PR number in case the workflow is being called in a pull request"
+        required: false
+        type: number
 
   push:
     branches: [release, master]
@@ -42,19 +47,55 @@ jobs:
           - 6379:6379
 
     steps:
-      # Checkout the code
+      - name: Figure out the PR number
+        run: echo ${{ github.event.pull_request.number }}
+
+      # Check out merge commit with the base branch in case this workflow is invoked via pull request
       - uses: actions/checkout@v2
+        if: inputs.pr != 0
+        with:
+          fetch-depth: 0
+          ref: "refs/pull/${{ inputs.pr }}/merge"
+
+      # Checkout the code in the current branch in case the workflow is called because of a branch push event
+      - uses: actions/checkout@v2
+        if: inputs.pr == 0
         with:
           fetch-depth: 0
 
+      # Timestamp will be used to create cache key
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +'%Y-%m-%dT%H:%M:%S')"
+
+      # In case this is second attempt try restoring status of the prior attempt from cache
+      - name: Restore the previous run result
+        uses: martijnhols/actions-cache@v3.0.2
+        with:
+          path: |
+            ~/run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
+
+      # Fetch prior run result
+      - name: Get the previous run result
+        id: run_result
+        run: cat ~/run_result 2>/dev/null || echo 'default'
+
+      # Incase of prior failure run the job
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
+
       # Setup Java
       - name: Set up JDK 1.11
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/setup-java@v1
         with:
           java-version: "11.0.10"
 
       # Retrieve maven dependencies from cache. After a successful run, these dependencies are cached again
       - name: Cache maven dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/cache@v2
         env:
           cache-name: cache-maven-dependencies
@@ -64,24 +105,9 @@ jobs:
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
 
-      # Here, the GITHUB_REF is of type /refs/head/<branch_name>. We extract branch_name from this by removing the
-      # first 11 characters. This can be used to build images for several branches
-      # Since this is an unreleased build, we get the latest released version number, increment the minor number in it,
-      # append a `-SNAPSHOT` at it's end to prepare the snapshot version number. This is used as the project's version.
-      - name: Get the version to tag the Docker image
-        id: vars
-        run: |
-          # Since this is an unreleased build, we set the version to incremented version number with a
-          # `-SNAPSHOT` suffix.
-          latest_released_version="$(git tag --list 'v*' --sort=-version:refname | head -1)"
-          echo "latest_released_version = $latest_released_version"
-          next_version="$(echo "$latest_released_version" | awk -F. -v OFS=. '{ $NF++; print }')"
-          echo "next_version = $next_version"
-          echo ::set-output name=version::$next_version-SNAPSHOT
-          echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
-
       # Build and test the code
       - name: Build and test
+        if: steps.run_result.outputs.run_result != 'success'
         env:
           APPSMITH_MONGODB_URI: "mongodb://localhost:27017/mobtools"
           APPSMITH_CLOUD_SERVICES_BASE_URL: "https://release-cs.appsmith.com"
@@ -96,9 +122,21 @@ jobs:
             -DprocessAllModules=true
           ./build.sh
 
+      # Restore the previous built bundle if present. If not push the newly built into the cache
+      - name: Restore the previous bundle
+        uses: actions/cache@v2
+        with:
+          path: |
+            app/server/dist/
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
+
       # Upload the build artifact so that it can be used by the test & deploy job in the workflow
       - name: Upload server build bundle
         uses: actions/upload-artifact@v2
         with:
           name: build
           path: app/server/dist/
+
+      - run: echo "::set-output name=run_result::success" > ~/run_result
