Update dp-from-branch.yml

diff --git a/.github/workflows/dp-from-branch.yml b/.github/workflows/dp-from-branch.yml
--- a/.github/workflows/dp-from-branch.yml
+++ b/.github/workflows/dp-from-branch.yml
@@ -11,7 +11,7 @@ on:
       skip-tests:
         description: "Flag to skip tests durin build"
         required: true
-        default: "release"
+        default: "true"
       uid:
         description: "Unique ID to store the run data in the db"
         required: true
@@ -20,28 +20,121 @@ on:
         required: true
 
 jobs:
-  write-job-details-to-db:
-    runs-on: ubuntu-latest
+  server-build:
+    runs-on: ubuntu-latest-8-cores
+
+
+    # Service containers to run with this job. Required for running tests
+    services:
+      # Label used to access the service container
+      redis:
+        # Docker Hub image for Redis
+        image: redis
+        ports:
+          # Opens tcp port 6379 on the host and service container
+          - 6379:6379
+
     steps:
-      - name: Install mongosh
+  
+      - name: Check out the build branch
+        uses: actions/checkout@v3
+        with:
+          # fetch-depth: 0
+          ref: ${{ github.event.inputs.branch }}
+     
+
+      # In case this is second attempt try restoring status of the prior attempt from cache
+      - name: Restore the previous run result
+        uses: actions/cache@v3
+        with:
+          path: |
+            ~/run_result
+          key: ${{ github.run_id }}-${{ github.job }}-server
+
+      # Fetch prior run result
+      - name: Get the previous run result
+        id: run_result
+        run: cat ~/run_result 2>/dev/null || echo 'default'
+
+      # In case of prior failure run the job
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
+
+      # Setup Java
+      - name: Set up JDK 17
+        if: steps.run_result.outputs.run_result != 'success'
+        uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '17'
+
+      # Retrieve maven dependencies from cache. After a successful run, these dependencies are cached again
+      - name: Cache maven dependencies
+        if: steps.run_result.outputs.run_result != 'success'
+        uses: actions/cache@v3
+        env:
+          cache-name: cache-maven-dependencies
+        with:
+          # maven dependencies are stored in `~/.m2` on Linux/macOS
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+
+      # Here, the GITHUB_REF is of type /refs/head/<branch_name>. We extract branch_name from this by removing the
+      # first 11 characters. This can be used to build images for several branches
+      # Since this is an unreleased build, we get the latest released version number, increment the minor number in it,
+      # append a `-SNAPSHOT` at it's end to prepare the snapshot version number. This is used as the project's version.
+      - name: Get the version to tag the Docker image
+        if: steps.run_result.outputs.run_result != 'success'
+        id: vars
         run: |
-          sudo apt-get update
-          sudo apt-get install -y wget gnupg
-          wget -qO - https://www.mongodb.org/static/pgp/server-5.0.asc | sudo apt-key add -
-          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
-          sudo apt-get update
-          sudo apt-get install -y mongodb-mongosh
-      - name: Update job data to mongoDB
+          # Since this is an unreleased build, we set the version to incremented version number with a
+          # `-SNAPSHOT` suffix.
+          latest_released_version="$(git tag --list 'v*' --sort=-version:refname | head -1)"
+          echo "latest_released_version = $latest_released_version"
+          next_version="$(echo "$latest_released_version" | awk -F. -v OFS=. '{ $NF++; print }')"
+          echo "next_version = $next_version"
+          echo version=$next_version-SNAPSHOT >> $GITHUB_OUTPUT
+          echo tag=$(echo ${GITHUB_REF:11}) >> $GITHUB_OUTPUT
+
+      # Build and test the code
+      - name: Build and test
+        if: steps.run_result.outputs.run_result != 'success'
+        env:
+          ACTIVE_PROFILE: test
+          APPSMITH_MONGODB_URI: "mongodb://localhost:27017/mobtools"
+          APPSMITH_CLOUD_SERVICES_BASE_URL: "https://release-cs.appsmith.com"
+          APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
+          APPSMITH_ENCRYPTION_PASSWORD: "password"
+          APPSMITH_ENCRYPTION_SALT: "salt"
+          APPSMITH_IS_SELF_HOSTED: false
+          APPSMITH_ENVFILE_PATH: /tmp/dummy.env
         run: |
-          #  mongosh 'mongodb+srv://appsmithadmin:W58w5yCN6ZY5Y42A@appsmith-infra-test-clu.zljea.mongodb.net/appsmiht-ce-github-dp-runs' --eval 'db.appsmiht-ce-github-dp-runs.insert( { run_id: ${{ github.run_id }}, uid: ${{ github.event.inputs.uid }}, status: "Started" } )'
-          mongosh 'mongodb+srv://appsmithadmin:W58w5yCN6ZY5Y42A@appsmith-infra-test-clu.zljea.mongodb.net/appsmiht-ce-github-dp-runs' --eval 'db.appsmiht-ce-github-dp-runs.update(
-                                                                  { _id:  ${{ github.event.inputs.uid }} },
-                                                                  {
-                                                                    $set: {
-                                                                      run_id: ${{ github.run_id }},
-                                                                      status: "BUILD IN PROGRESS"
-                                                                    }
-                                                                  }
-                                                                )'
-          #TODO Add mongo URI as secret
+          if [[ "${{ github.event.inputs.skip-tests }}" == "true" ]]
+          then
+            args=-DskipTests
+          fi
+          mvn --batch-mode versions:set \
+            -DnewVersion=${{ steps.vars.outputs.version }} \
+            -DgenerateBackupPoms=false \
+            -DprocessAllModules=true
+          ./build.sh $args
+
+      # Restore the previous built bundle if present. If not push the newly built into the cache
+      - name: Restore the previous bundle
+        uses: actions/cache@v3
+        with:
+          path: |
+            app/server/dist/
+          key: ${{ github.run_id }}-${{ github.job }}-server
+
+      # Upload the build artifact so that it can be used by the test & deploy job in the workflow
+      - name: Upload server build bundle
+        uses: actions/upload-artifact@v3
+        with:
+          name: server-build
+          path: app/server/dist/
+
+      - name: Save the status of the run
+        run: echo "run_result=success" >> $GITHUB_OUTPUT > ~/run_result
             
