🔧: Add change of script from suggestion from [PR38755](https://github.com/appsmithorg/appsmith/pull/38755)

diff --git a/.github/workflows/github-release.yml b/.github/workflows/github-release.yml
--- a/.github/workflows/github-release.yml
+++ b/.github/workflows/github-release.yml
@@ -213,7 +213,7 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2
+        uses: docker/setup-buildx-action@v3
 
       - name: Download the client build artifact
         uses: actions/download-artifact@v4
@@ -253,17 +253,20 @@ jobs:
       - name: Place server artifacts-es
         run: |
           if [[ -f scripts/prepare_server_artifacts.sh ]]; then
-            scripts/prepare_server_artifacts.sh
+          +   if ! scripts/prepare_server_artifacts.sh; then
+          +     echo "Error: Failed to prepare server artifacts"
+          +     exit 1
+          +   fi
           fi
 
       - name: Login to DockerHub
-        uses: docker/login-action@v2
+        uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_HUB_USERNAME2 }}
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN2 }}
 
       - name: Build and push Docker image
-        uses: docker/build-push-action@v3
+        uses: docker/build-push-action@v5
         with:
           context: .
           push: true
