Update integration-tests-command.yml

diff --git a/.github/workflows/integration-tests-command.yml b/.github/workflows/integration-tests-command.yml
--- a/.github/workflows/integration-tests-command.yml
+++ b/.github/workflows/integration-tests-command.yml
@@ -1,7 +1,6 @@
 name: Appsmith External Integration Test Workflow
 
 on:
-  workflow_dispatch:
   # This workflow is only triggered by the ok to test command dispatch
   repository_dispatch:
     types: [ok-to-test-command]
@@ -9,6 +8,10 @@ on:
 jobs:
   server-build:
     runs-on: ubuntu-latest
+    if: |
+      github.event_name == 'repository_dispatch' &&
+      github.event.client_payload.slash_command.sha != '' &&
+      contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha)
     defaults:
       run:
         working-directory: app/server
@@ -122,8 +125,14 @@ jobs:
           name: build
           path: app/server/dist/
 
+      # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
+
   build:
     runs-on: ubuntu-latest
+    if: github.event_name == 'repository_dispatch' &&
+      github.event.client_payload.slash_command.sha != '' &&
+      contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha)
     defaults:
       run:
         working-directory: app/client
@@ -328,12 +337,9 @@ jobs:
         working-directory: app/rts
     runs-on: ubuntu-latest
     # Only run this workflow for internally triggered events
-    if: |
-      github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'push' ||
-      (github.event_name == 'pull_request_review' &&
-      github.event.review.state == 'approved' &&
-      github.event.pull_request.head.repo.full_name == github.repository)
+    if: github.event_name == 'repository_dispatch' &&
+      github.event.client_payload.slash_command.sha != '' &&
+      contains(github.event.client_payload.pull_request.head.sha, github.event.client_payload.slash_command.sha)
 
     steps:
       # Checkout the code
@@ -560,12 +566,21 @@ jobs:
 
       - name: Load docker image
         if: success() && github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
+        env:
+          APPSMITH_LICENSE_KEY: ${{ secrets.APPSMITH_LICENSE_KEY }}
         working-directory: "."
         run: |
-          mkdir fatcontainerlocal
-          cd fatcontainerlocal          
+          mkdir -p fatcontainerlocal/stacks/configuration/
+          cd fatcontainerlocal
           docker run -d --name appsmith -p 80:80 -p 9001:9001 \
-            -v "$PWD/stacks:/appsmith-stacks" fatcontainer
+            -v "$PWD/stacks:/appsmith-stacks" appsmith/appsmith-ce
+          sudo chmod a+rw stacks/configuration/docker.env
+          sudo echo  "APPSMITH_LICENSE_KEY=$APPSMITH_LICENSE_KEY" >> stacks/configuration/docker.env
+      
+#      - name: Restart Appsmith
+#        if: steps.run_result.outputs.run_result != 'success'
+#        run: |
+#          docker restart appsmith
 
       - name: Use Node.js 14.15.4
         if: steps.run_result.outputs.run_result != 'success'
@@ -595,6 +610,8 @@ jobs:
           CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
           CYPRESS_S3_ACCESS_KEY: ${{ secrets.CYPRESS_S3_ACCESS_KEY }}
           CYPRESS_S3_SECRET_KEY: ${{ secrets.CYPRESS_S3_SECRET_KEY }}
+          CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN }}
+          CYPRESS_TEST_GITHUB_USER_NAME: ${{ secrets.CYPRESS_TEST_GITHUB_USER_NAME }}
           APPSMITH_DISABLE_TELEMETRY: true
           APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
           POSTGRES_PASSWORD: postgres
@@ -618,6 +635,8 @@ jobs:
           CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
           CYPRESS_S3_ACCESS_KEY: ${{ secrets.CYPRESS_S3_ACCESS_KEY }}
           CYPRESS_S3_SECRET_KEY: ${{ secrets.CYPRESS_S3_SECRET_KEY }}
+          CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN }}
+          CYPRESS_TEST_GITHUB_USER_NAME: ${{ secrets.CYPRESS_TEST_GITHUB_USER_NAME }}
           APPSMITH_DISABLE_TELEMETRY: true
           APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
           COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
@@ -651,6 +670,8 @@ jobs:
           CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
           CYPRESS_S3_ACCESS_KEY: ${{ secrets.CYPRESS_S3_ACCESS_KEY }}
           CYPRESS_S3_SECRET_KEY: ${{ secrets.CYPRESS_S3_SECRET_KEY }}
+          CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN }}
+          CYPRESS_TEST_GITHUB_USER_NAME: ${{ secrets.CYPRESS_TEST_GITHUB_USER_NAME }}
           APPSMITH_DISABLE_TELEMETRY: true
           APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
           COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
@@ -661,7 +682,7 @@ jobs:
           install: false
           parallel: true
           config-file: cypress_fat.json
-          group: "Electrons on Github Action Fat Container"
+          group: "Electrons on Github Action"
           spec: ${{ env.failed_spec_env }}
           working-directory: app/client
           # tag will be either "push" or "pull_request"
@@ -763,7 +784,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        job: [0, 1, 2]
+        job: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
+
     # Service containers to run with this job. Required for running tests
     services:
       # Label used to access the service container
@@ -970,8 +992,7 @@ jobs:
           install: false
           parallel: true
           group: "Electrons on Github Action"
-          #spec: "cypress/integration/Smoke_TestSuite/**/*"
-          spec: "cypress/integration/Smoke_TestSuite/testingreuse/*"
+          spec: "cypress/integration/Smoke_TestSuite/**/*"
           working-directory: app/client
           # tag will be either "push" or "pull_request"
           tag: ${{ github.event_name }}
@@ -993,6 +1014,8 @@ jobs:
           CYPRESS_TESTPASSWORD2: ${{ secrets.CYPRESS_TESTPASSWORD1 }}
           CYPRESS_S3_ACCESS_KEY: ${{ secrets.CYPRESS_S3_ACCESS_KEY }}
           CYPRESS_S3_SECRET_KEY: ${{ secrets.CYPRESS_S3_SECRET_KEY }}
+          CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.CYPRESS_GITHUB_PERSONAL_ACCESS_TOKEN }}
+          CYPRESS_TEST_GITHUB_USER_NAME: ${{ secrets.CYPRESS_TEST_GITHUB_USER_NAME }}
           APPSMITH_DISABLE_TELEMETRY: true
           APPSMITH_GOOGLE_MAPS_API_KEY: ${{ secrets.APPSMITH_GOOGLE_MAPS_API_KEY }}
           COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
@@ -1026,8 +1049,8 @@ jobs:
       - name: Incase of test failures copy them to a file
         if: failure()
         run: |
-          cd /home/runner/work/appsmith/appsmith/app/client/cypress/
-          find screenshots -type d|grep spec |sed 's/screenshots/cypress\/integration/g' > ~/failed_spec/failed_spec-${{ matrix.job }}
+          cd ${{ github.workspace }}/app/client/cypress/
+          find screenshots -type d|grep -i spec |sed 's/screenshots/cypress\/integration/g' > ~/failed_spec/failed_spec-${{ matrix.job }}
 
       # Upload failed test list using common path for all matrix job
       - name: Upload failed test list artifact
@@ -1083,8 +1106,11 @@ jobs:
           name: server-logs-${{ matrix.job }}
           path: app/server/server-logs.log
 
+      # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
+
   ui-test-result:
-    needs: [ui-test, fat-conatiner-test]
+    needs: ui-test
     # Only run if the ui-test with matrices step is successful
     if: always()
     runs-on: ubuntu-latest
@@ -1196,7 +1222,7 @@ jobs:
         run: echo "$PAYLOAD_CONTEXT"
 
   package:
-    needs: [ui-test, fat-conatiner-test]
+    needs: ui-test
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -1296,17 +1322,46 @@ jobs:
         with:
           ref: "refs/pull/${{ github.event.client_payload.pull_request.number }}/merge"
 
+      # Timestamp will be used to create cache key
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +'%Y-%m-%dT%H:%M:%S')"
+
+      # In case this is second attempt try restoring status of the prior attempt from cache
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-
+
+      # Fetch prior run result
+      - name: Get the previous run result
+        id: run_result
+        run: cat ~/run_result 2>/dev/null || echo 'default'
+
+      # Incase of prior failure run the job
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
+
+      # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
+
       - name: Use Node.js 14.15.4
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/setup-node@v1
         with:
           node-version: "14.15.4"
 
       - name: Get yarn cache directory path
+        if: steps.run_result.outputs.run_result != 'success'
         id: yarn-dep-cache-dir-path
         run: echo "::set-output name=dir::$(yarn cache dir)"
 
       # Retrieve npm dependencies from cache. After a successful run, these dependencies are cached again
       - name: Cache npm dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         id: yarn-dep-cache
         uses: actions/cache@v2
         env:
@@ -1320,15 +1375,18 @@ jobs:
 
       # Install all the dependencies
       - name: Install dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         run: yarn install
 
       - name: Download the react build artifact
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/download-artifact@v2
         with:
           name: build
           path: app/client/build
 
       - name: Download the server build artifact
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/download-artifact@v2
         with:
           name: build
@@ -1336,6 +1394,7 @@ jobs:
 
       # Start server
       - name: start server
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/server
         env:
           APPSMITH_MONGODB_URI: "mongodb://localhost:27017/mobtools"
@@ -1355,10 +1414,12 @@ jobs:
           ./scripts/start-dev-server.sh &> server-logs.log &
 
       - name: Wait for 30 seconds for server to start
+        if: steps.run_result.outputs.run_result != 'success'
         run: |
           sleep 30s
 
       - name: Exit if Server hasnt started
+        if: steps.run_result.outputs.run_result != 'success'
         run: |
           if [[ `ps -ef | grep "server-1.0-SNAPSHOT" | grep java |wc -l` == 0 ]]; then
              echo "Server Not Started";
@@ -1368,11 +1429,13 @@ jobs:
            fi
 
       - name: Installing Yarn serve
+        if: steps.run_result.outputs.run_result != 'success'
         run: |
           yarn global add serve
           echo "$(yarn global bin)" >> $GITHUB_PATH
 
       - name: Setting up the perf tests
+        if: steps.run_result.outputs.run_result != 'success'
         shell: bash
         env:
           APPSMITH_SSL_CERTIFICATE: ${{ secrets.APPSMITH_SSL_CERTIFICATE }}
@@ -1393,15 +1456,18 @@ jobs:
           ./cypress/setup-test.sh
 
       - name: Installing performance tests dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/client/perf
         shell: bash
         run: yarn install
 
       - name: Change test script permissions
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/client/perf
         run: chmod +x ./start-test.sh
 
       - name: Run performance tests
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/client/perf
         shell: bash
         env:
@@ -1409,10 +1475,21 @@ jobs:
           APPSMITH_SSL_KEY: ${{ secrets.APPSMITH_SSL_KEY }}
           CYPRESS_TESTUSERNAME1: ${{ secrets.CYPRESS_TESTUSERNAME9 }}
           CYPRESS_TESTPASSWORD1: ${{ secrets.CYPRESS_TESTPASSWORD9 }}
+          APPSMITH_PERF_SUPABASE_SECRET: ${{ secrets.APPSMITH_PERF_SUPABASE_SECRET }}
           APPSMITH_DISABLE_TELEMETRY: true
           POSTGRES_PASSWORD: postgres
           NODE_TLS_REJECT_UNAUTHORIZED: "0"
         run: ./start-test.sh
+
+      # Restore the previous built bundle if present. If not push the newly built into the cache
+      - name: Restore the previous bundle
+        uses: actions/cache@v2
+        with:
+          path: |
+            app/client/perf/traces
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
 
       - uses: actions/upload-artifact@v2
         with:
@@ -1433,3 +1510,6 @@ jobs:
             UI Performance test run logs and artifacts: <https://github.com/appsmithorg/appsmith/actions/runs/${{ github.run_id }}>.
             Commit: `${{ github.event.client_payload.slash_command.sha }}`.
             Results: ${{ steps.read_summary.outputs.contents }}
+
+        # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
