test: Reuse performance actions (#10913)

diff --git a/.github/workflows/integration-tests-command.yml b/.github/workflows/integration-tests-command.yml
--- a/.github/workflows/integration-tests-command.yml
+++ b/.github/workflows/integration-tests-command.yml
@@ -879,17 +879,46 @@ jobs:
         with:
           ref: "refs/pull/${{ github.event.client_payload.pull_request.number }}/merge"
 
+      # Timestamp will be used to create cache key
+      - id: timestamp
+        run: echo "::set-output name=timestamp::$(timestamp +'%Y-%m-%dT%H:%M:%S')"
+
+      # In case this is second attempt try restoring status of the prior attempt from cache
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-
+
+      # Fetch prior run result
+      - name: Get the previous run result
+        id: run_result
+        run: cat ~/run_result 2>/dev/null || echo 'default'
+
+      # Incase of prior failure run the job
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
+
+      # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
+
       - name: Use Node.js 14.15.4
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/setup-node@v1
         with:
           node-version: "14.15.4"
 
       - name: Get yarn cache directory path
+        if: steps.run_result.outputs.run_result != 'success'
         id: yarn-dep-cache-dir-path
         run: echo "::set-output name=dir::$(yarn cache dir)"
 
       # Retrieve npm dependencies from cache. After a successful run, these dependencies are cached again
       - name: Cache npm dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         id: yarn-dep-cache
         uses: actions/cache@v2
         env:
@@ -903,15 +932,18 @@ jobs:
 
       # Install all the dependencies
       - name: Install dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         run: yarn install
 
       - name: Download the react build artifact
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/download-artifact@v2
         with:
           name: build
           path: app/client/build
 
       - name: Download the server build artifact
+        if: steps.run_result.outputs.run_result != 'success'
         uses: actions/download-artifact@v2
         with:
           name: build
@@ -919,6 +951,7 @@ jobs:
 
       # Start server
       - name: start server
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/server
         env:
           APPSMITH_MONGODB_URI: "mongodb://localhost:27017/mobtools"
@@ -938,10 +971,12 @@ jobs:
           ./scripts/start-dev-server.sh &> server-logs.log &
 
       - name: Wait for 30 seconds for server to start
+        if: steps.run_result.outputs.run_result != 'success'
         run: |
           sleep 30s
 
       - name: Exit if Server hasnt started
+        if: steps.run_result.outputs.run_result != 'success'
         run: |
           if [[ `ps -ef | grep "server-1.0-SNAPSHOT" | grep java |wc -l` == 0 ]]; then
              echo "Server Not Started";
@@ -951,11 +986,13 @@ jobs:
            fi
 
       - name: Installing Yarn serve
+        if: steps.run_result.outputs.run_result != 'success'
         run: |
           yarn global add serve
           echo "$(yarn global bin)" >> $GITHUB_PATH
 
       - name: Setting up the perf tests
+        if: steps.run_result.outputs.run_result != 'success'
         shell: bash
         env:
           APPSMITH_SSL_CERTIFICATE: ${{ secrets.APPSMITH_SSL_CERTIFICATE }}
@@ -976,15 +1013,18 @@ jobs:
           ./cypress/setup-test.sh
 
       - name: Installing performance tests dependencies
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/client/perf
         shell: bash
         run: yarn install
 
       - name: Change test script permissions
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/client/perf
         run: chmod +x ./start-test.sh
 
       - name: Run performance tests
+        if: steps.run_result.outputs.run_result != 'success'
         working-directory: app/client/perf
         shell: bash
         env:
@@ -996,6 +1036,16 @@ jobs:
           POSTGRES_PASSWORD: postgres
           NODE_TLS_REJECT_UNAUTHORIZED: "0"
         run: ./start-test.sh
+
+      # Restore the previous built bundle if present. If not push the newly built into the cache
+      - name: Restore the previous bundle
+        uses: actions/cache@v2
+        with:
+          path: |
+            app/client/perf/traces
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
 
       - uses: actions/upload-artifact@v2
         with:
@@ -1016,3 +1066,6 @@ jobs:
             UI Performance test run logs and artifacts: <https://github.com/appsmithorg/appsmith/actions/runs/${{ github.run_id }}>.
             Commit: `${{ github.event.client_payload.slash_command.sha }}`.
             Results: ${{ steps.read_summary.outputs.contents }}
+
+        # Set status = success
+      - run: echo "::set-output name=run_result::success" > ~/run_result
