Modify existing workflow to build fat container image

diff --git a/.github/workflows/test-build-docker-image.yml b/.github/workflows/test-build-docker-image.yml
--- a/.github/workflows/test-build-docker-image.yml
+++ b/.github/workflows/test-build-docker-image.yml
@@ -1,12 +1,29 @@
-name: Test and Build Fat
+name: Test, build and push Docker Image
 
 on:
   # This line enables manual triggering of this workflow.
   workflow_dispatch:
 
+  pull_request_review:
+    types: [submitted]
+    branches: [release, master]
+    paths:
+      - "app/client/**"
+      - "app/server/**"
+      - "!app/client/cypress/manual_TestSuite/**"
+
+  # trigger for pushes to release and master
+  push:
+    branches: [release, release-frozen, master]
+    paths:
+      - "app/client/**"
+      - "app/server/**"
+      - "!app/client/cypress/manual_TestSuite/**"
+
+# Change the working directory for all the jobs in this workflow
 defaults:
   run:
-    shell: bash
+    working-directory: app/client
 
 jobs:
   buildClient:
@@ -15,20 +32,21 @@ jobs:
     if: |
       github.event_name == 'workflow_dispatch' ||
       github.event_name == 'push' ||
-      (github.event_name == 'pull_request_review' && github.event.review.state == 'approved')
-
+      (github.event_name == 'pull_request_review' &&
+      github.event.review.state == 'approved')
     runs-on: ubuntu-latest
-
     defaults:
       run:
         working-directory: app/client
         shell: bash
 
     steps:
+      # Checkout the code
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
+      # Checkout the code
       - name: Checkout the merged commit from PR and base branch
         if: github.event_name == 'pull_request_review'
         uses: actions/checkout@v2
@@ -46,14 +64,30 @@ jobs:
         run: echo ${{ github.event.pull_request.number }}
 
       - name: Use Node.js 14.15.4
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v1
         with:
           node-version: "14.15.4"
-          cache: "yarn"
-          cache-dependency-path: "app/client/yarn.lock"
 
+      - name: Get yarn cache directory path
+        id: yarn-dep-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+
+      # Retrieve npm dependencies from cache. After a successful run, these dependencies are cached again
+      - name: Cache npm dependencies
+        id: yarn-dep-cache
+        uses: actions/cache@v2
+        env:
+          cache-name: cache-yarn-dependencies
+        with:
+          path: |
+            ${{ steps.yarn-dep-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-dep-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-dep-
+
+      # Install all the dependencies
       - name: Install dependencies
-        run: yarn install --frozen-lockfile
+        run: yarn install
 
       - name: Set the build environment based on the branch
         id: vars
@@ -72,11 +106,6 @@ jobs:
           next_version="$(echo "$latest_released_version" | awk -F. -v OFS=. '{ $NF++; print }')"
           echo "next_version = $next_version"
           echo ::set-output name=version::$next_version-SNAPSHOT
-
-      - name: Run the jest tests
-        run: |
-          REACT_APP_ENVIRONMENT=${{steps.vars.outputs.REACT_APP_ENVIRONMENT}} \
-            echo yarn run test:unit
 
       # We burn React environment & the Segment analytics key into the build itself.
       # This is to ensure that we don't need to configure it in each installation
@@ -101,22 +130,24 @@ jobs:
           path: app/client/build/
 
   buildServer:
+    defaults:
+        run:
+            working-directory: app/server
+    runs-on: ubuntu-latest
     # Only run this workflow for internally triggered events
     if: |
       github.event.pull_request.head.repo.full_name == github.repository ||
       github.event_name == 'push' ||
       github.event_name == 'workflow_dispatch'
 
-    runs-on: ubuntu-latest
-
-    defaults:
-      run:
-        working-directory: app/server
-
+    # Service containers to run with this job. Required for running tests
     services:
+      # Label used to access the service container
       redis:
+        # Docker Hub image for Redis
         image: redis
         ports:
+          # Opens tcp port 6379 on the host and service container
           - 6379:6379
       mongo:
         image: mongo
@@ -124,14 +155,16 @@ jobs:
           - 27017:27017
 
     steps:
+      # Checkout the code
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
+
+      # Setup Java
+      - name: Set up JDK 1.11
+        uses: actions/setup-java@v1
         with:
-          distribution: "adopt"
           java-version: "11.0.10"
 
       # Retrieve maven dependencies from cache. After a successful run, these dependencies are cached again
@@ -140,6 +173,7 @@ jobs:
         env:
           cache-name: cache-maven-dependencies
         with:
+          # maven dependencies are stored in `~/.m2` on Linux/macOS
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
@@ -160,18 +194,20 @@ jobs:
           echo ::set-output name=version::$next_version-SNAPSHOT
           echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
 
-      - name: Test and build package
+      - name: Test and Build package
         env:
-          APPSMITH_MONGODB_URI: "mongodb://localhost:27017/appsmith"
+          APPSMITH_MONGODB_URI: "mongodb://localhost:27017/mobtools"
           APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
           APPSMITH_ENCRYPTION_PASSWORD: "password"
           APPSMITH_ENCRYPTION_SALT: "salt"
           APPSMITH_IS_SELF_HOSTED: "false"
           APPSMITH_CLOUD_SERVICES_BASE_URL: "https://release-cs.appsmith.com"
-          APPSMITH_CLOUD_SERVICES_USERNAME: ""
-          APPSMITH_CLOUD_SERVICES_PASSWORD: ""
         run: |
-          ./build.sh
+          mvn --batch-mode versions:set \
+            -DnewVersion=${{ steps.vars.outputs.version }} \
+            -DgenerateBackupPoms=false \
+            -DprocessAllModules=true
+          mvn --batch-mode package
 
       # Upload the build artifact so that it can be used by the test & deploy job in the workflow
       - name: Upload server build bundle
@@ -181,20 +217,14 @@ jobs:
           path: app/server/dist/
 
   ui-test:
-    needs:
-      - buildClient
-      - buildServer
-
+    needs: [buildClient, buildServer]
     # Only run if the build step is successful
     if: success()
-
     runs-on: ubuntu-latest
-
     defaults:
       run:
         working-directory: app/client
         shell: bash
-
     strategy:
       fail-fast: false
       matrix:
@@ -215,6 +245,7 @@ jobs:
           - 27017:27017
 
     steps:
+      # Checkout the code
       - name: Checkout the merged commit from PR and base branch
         if: github.event_name == 'pull_request_review'
         uses: actions/checkout@v2
@@ -225,10 +256,10 @@ jobs:
         if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
         uses: actions/checkout@v2
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v2
+      # Setup Java
+      - name: Set up JDK 1.11
+        uses: actions/setup-java@v1
         with:
-          distribution: "adopt"
           java-version: "11.0.10"
 
       - name: Download the server build artifact
@@ -272,20 +303,23 @@ jobs:
           APPSMITH_REDIS_URL: "redis://127.0.0.1:6379"
           APPSMITH_ENCRYPTION_PASSWORD: "password"
           APPSMITH_ENCRYPTION_SALT: "salt"
-          APPSMITH_IS_SELF_HOSTED: "false"
+          APPSMITH_IS_SELF_HOSTED: false
           APPSMITH_CLOUD_SERVICES_BASE_URL: "https://release-cs.appsmith.com"
           APPSMITH_CLOUD_SERVICES_USERNAME: ""
           APPSMITH_CLOUD_SERVICES_PASSWORD: ""
         run: |
-          nohup ./scripts/start-dev-server.sh 2>&1 &
+            ls -l
+            ls -l scripts/
+            ls -l dist/
+            nohup ./scripts/start-dev-server.sh 2>&1 &
 
       - name: Wait for 30 seconds for server to start
         run: |
           sleep 30s
 
-      - name: Exit if Server hasnt started
+      - name: "Exit if Server hasn't started"
         run: |
-          lsof -i :8080
+          lsof -i :8080 || true;
           if [[ `ps -ef | grep "server-1.0-SNAPSHOT" | grep java |wc -l` == 0 ]]; then
             echo "Server Not Started";
             exit 1;
@@ -294,15 +328,30 @@ jobs:
           fi
 
       - name: Use Node.js 14.15.4
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v1
         with:
           node-version: "14.15.4"
-          cache: "yarn"
-          cache-dependency-path: "app/client/yarn.lock"
 
+      - name: Get yarn cache directory path
+        id: yarn-dep-cache-dir-path
+        run: echo "::set-output name=dir::$(yarn cache dir)"
+
+      # Retrieve npm dependencies from cache. After a successful run, these dependencies are cached again
+      - name: Cache npm dependencies
+        id: yarn-dep-cache
+        uses: actions/cache@v2
+        env:
+          cache-name: cache-yarn-dependencies
+        with:
+          path: |
+            ${{ steps.yarn-dep-cache-dir-path.outputs.dir }}
+          key: ${{ runner.os }}-yarn-dep-${{ hashFiles('**/yarn.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-yarn-dep-
+
+      # Install all the dependencies
       - name: Install dependencies
-        run: |
-          yarn install --frozen-lockfile
+        run: yarn install
 
       - name: Download the react build artifact
         uses: actions/download-artifact@v2
@@ -365,8 +414,8 @@ jobs:
           tag: ${{ github.event_name }}
           env: "NODE_ENV=development"
 
-      - name: Upload the screenshots as artifacts if there's a failure
-        uses: actions/upload-artifact@v1
+      # Upload the screenshots as artifacts if there's a failure
+      - uses: actions/upload-artifact@v1
         if: failure()
         with:
           name: cypress-screenshots-${{ matrix.job }}
@@ -374,14 +423,19 @@ jobs:
 
   ui-test-result:
     needs: ui-test
-
+    if: always()
     runs-on: ubuntu-latest
-
+    defaults:
+      run:
+        shell: bash
     steps:
+      - run: echo "All ui-test matrices completed"
+
       - name: Return status for ui-matrix
         run: |
           if [[ "${{ needs.ui-test.result }}" == "success" ]]; then
             echo "Integration tests completed successfully!";
+            exit 0;
           elif [[ "${{ needs.ui-test.result }}" == "skipped" ]]; then
             echo "Integration tests were skipped";
             exit 1;
@@ -392,13 +446,15 @@ jobs:
 
   package:
     needs: ui-test
-
-    # Run this job only if all the previous steps are a success and the reference if the release or master branch
-    if: success() && (github.ref == 'refs/heads/release' || github.ref == 'refs/heads/master')
-
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: app/client
+    # Run this job only if all the previous steps are a success and the reference if the release or master branch
+    if: (success() && github.ref == 'refs/heads/release') || github.ref == 'refs/heads/master'
 
     steps:
+      # Checkout the code
       - name: Checkout the merged commit from PR and base branch
         if: github.event_name == 'pull_request_review'
         uses: actions/checkout@v2
@@ -415,35 +471,65 @@ jobs:
           name: build
           path: app/client/build
 
-      - name: Download the server build artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: build
-          path: app/server/dist
-
       # Here, the GITHUB_REF is of type /refs/head/<branch_name>. We extract branch_name from this by removing the
       # first 11 characters. This can be used to build images for several branches
       - name: Get the version to tag the Docker image
         id: branch_name
         run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
 
+      # Build release Docker image and push to Docker Hub
+      - name: Push client release image to Docker Hub
+        if: success() && github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
+        run: |
+          docker build -t ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${{steps.branch_name.outputs.tag}} .
+          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
+          docker push ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${{steps.branch_name.outputs.tag}}
+
+      # Build master Docker image and push to Docker Hub
+      - name: Push client master image to Docker Hub with commit tag
+        if: success() && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
+        run: |
+          docker build -t ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${GITHUB_SHA} .
+          docker build -t ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:nightly .
+          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
+          docker push ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:${GITHUB_SHA}
+          docker push ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-editor:nightly
+
+      # Build release Docker image and push to Docker Hub
+      - name: Push server release image to Docker Hub
+        if: success() && github.ref == 'refs/heads/release'
+        run: |
+          docker build --build-arg APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }} -t ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${{steps.vars.outputs.tag}} .
+          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
+          docker push ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${{steps.vars.outputs.tag}}
+
+      # Build master Docker image and push to Docker Hub
+      - name: Push server master image to Docker Hub with commit tag
+        if: success() && github.ref == 'refs/heads/master'
+        run: |
+          docker build --build-arg APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }} -t ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${GITHUB_SHA} .
+          docker build --build-arg APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }} -t ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:nightly .
+          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
+          docker push ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:${GITHUB_SHA}
+          docker push ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-server:nightly
+
       - name: Build and push release image to Docker Hub
         if: success() && github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
         run: |
           docker build \
             --build-arg APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }} \
-            --tag ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith:${{steps.branch_name.outputs.tag}} \
+            --tag ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${{steps.branch_name.outputs.tag}} \
             .
           echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
-          docker push --all-tags ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith
+          docker push --all-tags ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce
 
-      - name: Build and push production image to Docker Hub with commit tag
+      - name: Build and push master image to Docker Hub with commit tag
         if: success() && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
         run: |
           docker build \
             --build-arg APPSMITH_SEGMENT_CE_KEY=${{ secrets.APPSMITH_SEGMENT_CE_KEY }} \
-            --tag ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith:${GITHUB_SHA} \
-            --tag ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith:nightly \
+            --tag ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${GITHUB_SHA} \
+            --tag ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:nightly \
             .
           echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
-          docker push --all-tags ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith
+          docker push --all-tags ${{ secrets.DOCKER_HUB_ORGANIZATION }}/appsmith-ce
