new update for failing job

diff --git a/.github/workflows/test-vulnerabilities-data.yml b/.github/workflows/test-vulnerabilities-data.yml
--- a/.github/workflows/test-vulnerabilities-data.yml
+++ b/.github/workflows/test-vulnerabilities-data.yml
@@ -61,4 +61,20 @@ jobs:
             "${{ github.event.pull_request.number }}" \
             "${{ github.event.pull_request.html_url }}" \
             "${{ github.run_id }}"
-            
+
+      - name: Check for new vulnerabilities in Scout and Trivy files
+        if: always()
+        run: |
+          # Check if Scout vulnerabilities file is not empty
+          if [ -s "scout_new_vulnerabilities.csv" ]; then
+            echo "Scout vulnerabilities detected."
+            cat scout_new_vulnerabilities.csv
+            exit 1  # Fail the job if data exists
+          fi
+              
+          # Check if Trivy vulnerabilities file is not empty
+          if [ -s "trivy_new_vulnerabilities.csv" ]; then
+            echo "Trivy vulnerabilities detected."
+            cat trivy_new_vulnerabilities.csv
+            exit 1  # Fail the job if data exists
+          fi
