Update test-build-docker-image.yml

diff --git a/.github/workflows/test-build-docker-image.yml b/.github/workflows/test-build-docker-image.yml
--- a/.github/workflows/test-build-docker-image.yml
+++ b/.github/workflows/test-build-docker-image.yml
@@ -45,98 +45,98 @@ jobs:
     with:
       pr: 0
 
-  perf-test:
-    needs: [build-docker-image]
-    # Only run if the build step is successful
-    if: success()
-    name: perf-test
-    uses: ./.github/workflows/perf-test.yml
-    secrets: inherit
-    with:
-      pr: 0
+#   perf-test:
+#     needs: [build-docker-image]
+#     # Only run if the build step is successful
+#     if: success()
+#     name: perf-test
+#     uses: ./.github/workflows/perf-test.yml
+#     secrets: inherit
+#     with:
+#       pr: 0
 
-  ci-test:
-    needs: [build-docker-image]
-    # Only run if the build step is successful
-    if: success()
-    name: ci-test
-    uses: ./.github/workflows/ci-test.yml
-    secrets: inherit
-    with:
-      pr: 0
+#   ci-test:
+#     needs: [build-docker-image]
+#     # Only run if the build step is successful
+#     if: success()
+#     name: ci-test
+#     uses: ./.github/workflows/ci-test.yml
+#     secrets: inherit
+#     with:
+#       pr: 0
 
-  ci-test-result:
-    needs: [ci-test]
-    if: always() &&
-      (github.event_name == 'workflow_dispatch' ||
-      github.event_name == 'push' ||
-      (github.event_name == 'pull_request_review' &&
-      github.event.review.state == 'approved' &&
-      github.event.pull_request.head.repo.full_name == github.repository))
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        shell: bash
-    steps:
-      - run: echo "All ci-test matrices completed"
+#   ci-test-result:
+#     needs: [ci-test]
+#     if: always() &&
+#       (github.event_name == 'workflow_dispatch' ||
+#       github.event_name == 'push' ||
+#       (github.event_name == 'pull_request_review' &&
+#       github.event.review.state == 'approved' &&
+#       github.event.pull_request.head.repo.full_name == github.repository))
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run:
+#         shell: bash
+#     steps:
+#       - run: echo "All ci-test matrices completed"
 
-      # Deleting the existing dir's if any
-      - name: Delete existing directories
-        if: needs.ci-test.result != 'success'
-        run: |
-          rm -f ~/failed_spec_ci
-          rm -f ~/combined_failed_spec_ci
+#       # Deleting the existing dir's if any
+#       - name: Delete existing directories
+#         if: needs.ci-test.result != 'success'
+#         run: |
+#           rm -f ~/failed_spec_ci
+#           rm -f ~/combined_failed_spec_ci
 
-      # Download failed_spec_ci list for all CI container jobs
-      - uses: actions/download-artifact@v3
-        if: needs.ci-test.result != 'success'
-        id: download_ci
-        with:
-          name: failed-spec-ci-${{github.run_attempt}}
-          path: ~/failed_spec_ci
+#       # Download failed_spec_ci list for all CI container jobs
+#       - uses: actions/download-artifact@v3
+#         if: needs.ci-test.result != 'success'
+#         id: download_ci
+#         with:
+#           name: failed-spec-ci-${{github.run_attempt}}
+#           path: ~/failed_spec_ci
 
-      # In case for any ci job failure, create combined failed spec
-      - name: "combine all specs for CI"
-        if: needs.ci-test.result != 'success'
-        run: |
-          rm -f ~/combined_failed_spec_ci
-          cat ~/failed_spec_ci/failed_spec_ci* >> ~/combined_failed_spec_ci
+#       # In case for any ci job failure, create combined failed spec
+#       - name: "combine all specs for CI"
+#         if: needs.ci-test.result != 'success'
+#         run: |
+#           rm -f ~/combined_failed_spec_ci
+#           cat ~/failed_spec_ci/failed_spec_ci* >> ~/combined_failed_spec_ci
 
-      # Force save the CI failed spec list into a cache
-      - name: Store the combined run result for CI
-        if: needs.ci-test.result != 'success'
-        uses: martijnhols/actions-cache/save@v3
-        with:
-          path: |
-            ~/combined_failed_spec_ci
-          key: ${{ github.run_id }}-"ci-test-result"
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}
+#       # Force save the CI failed spec list into a cache
+#       - name: Store the combined run result for CI
+#         if: needs.ci-test.result != 'success'
+#         uses: martijnhols/actions-cache/save@v3
+#         with:
+#           path: |
+#             ~/combined_failed_spec_ci
+#           key: ${{ github.run_id }}-"ci-test-result"
+#           restore-keys: |
+#             ${{ github.run_id }}-${{ github.job }}
 
-      # Upload combined failed CI spec list to a file
-      # This is done for debugging.
-      - name: upload combined failed spec
-        if: needs.ci-test.result != 'success'
-        uses: actions/upload-artifact@v3
-        with:
-          name: combined_failed_spec_ci
-          path: ~/combined_failed_spec_ci
+#       # Upload combined failed CI spec list to a file
+#       # This is done for debugging.
+#       - name: upload combined failed spec
+#         if: needs.ci-test.result != 'success'
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: combined_failed_spec_ci
+#           path: ~/combined_failed_spec_ci
 
-      - name: Return status for ui-matrix
-        run: |
-          if [[ "${{ needs.ci-test.result }}" == "success" ]]; then
-            echo "Integration tests completed successfully!";
-            exit 0;
-          elif [[ "${{ needs.ci-test.result }}" == "skipped" ]]; then
-            echo "Integration tests were skipped";
-            exit 1;
-          else
-            echo "Integration tests have failed";
-            exit 1;
-          fi
+#       - name: Return status for ui-matrix
+#         run: |
+#           if [[ "${{ needs.ci-test.result }}" == "success" ]]; then
+#             echo "Integration tests completed successfully!";
+#             exit 0;
+#           elif [[ "${{ needs.ci-test.result }}" == "skipped" ]]; then
+#             echo "Integration tests were skipped";
+#             exit 1;
+#           else
+#             echo "Integration tests have failed";
+#             exit 1;
+#           fi
 
   package:
-    needs: ci-test
+    needs: [build-docker-image]
     runs-on: ubuntu-latest
     # Set permissions since we're using OIDC token authentication between Depot and GitHub
     permissions:
@@ -144,7 +144,7 @@ jobs:
       id-token: write
 
     # Run this job irrespective of tests failing, if this is the release branch; or only if the tests pass, if this is the master branch.
-    if: (success() && github.ref == 'refs/heads/master') ||
+    if: (github.ref == 'refs/heads/master') ||
       ( always() &&
       (
       github.event_name == 'workflow_dispatch' ||
@@ -216,7 +216,7 @@ jobs:
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 
       - name: Build and push release image to Docker Hub
-        if: success() && github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
+        if: github.ref == 'refs/heads/release' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
         uses: depot/build-push-action@v1
         with:
           context: .
@@ -228,7 +228,7 @@ jobs:
             ${{ vars.DOCKER_HUB_ORGANIZATION }}/appsmith-ce:${{steps.vars.outputs.tag}}
 
       - name: Build and push master image to Docker Hub with commit tag
-        if: success() && github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
+        if: github.ref == 'refs/heads/master' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
         uses: depot/build-push-action@v1
         with:
           context: .
