Removing the restore bundle to get fresh install

diff --git a/.github/workflows/test-build-docker-image.yml b/.github/workflows/test-build-docker-image.yml
--- a/.github/workflows/test-build-docker-image.yml
+++ b/.github/workflows/test-build-docker-image.yml
@@ -320,24 +320,24 @@ jobs:
       - id: timestamp
         run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M:%S')"
 
-      # In case this is second attempt try restoring status of the prior attempt from cache
-      - name: Restore the previous run result
-        uses: actions/cache@v2
-        with:
-          path: |
-            ~/run_result
-          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}-
+      # # In case this is second attempt try restoring status of the prior attempt from cache
+      # - name: Restore the previous run result
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: |
+      #       ~/run_result
+      #     key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+      #     restore-keys: |
+      #       ${{ github.run_id }}-${{ github.job }}-
 
-      # Fetch prior run result
-      - name: Get the previous run result
-        id: run_result
-        run: cat ~/run_result 2>/dev/null || echo 'default'
+      # # Fetch prior run result
+      # - name: Get the previous run result
+      #   id: run_result
+      #   run: cat ~/run_result 2>/dev/null || echo 'default'
 
-      # Incase of prior failure run the job
-      - if: steps.run_result.outputs.run_result != 'success'
-        run: echo "I'm alive!" && exit 0
+      # # Incase of prior failure run the job
+      # - if: steps.run_result.outputs.run_result != 'success'
+      #   run: echo "I'm alive!" && exit 0
 
       - name: Use Node.js 16.14.0
         if: steps.run_result.outputs.run_result != 'success'
@@ -371,24 +371,24 @@ jobs:
           ls -l dist/node_modules
 
       # Restore the previous built bundle if present. If not push the newly built into the cache
-      - name: Restore the previous bundle
-        uses: actions/cache@v2
-        with:
-          path: |
-            app/rts/dist/
-          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}
+      # - name: Restore the previous bundle
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: |
+      #       app/rts/dist/
+      #     key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+      #     restore-keys: |
+      #       ${{ github.run_id }}-${{ github.job }}
 
       # Restore the previous built bundle if present. If not push the newly built into the cache
-      - name: Restore the previous bundle
-        uses: actions/cache@v2
-        with:
-          path: |
-            app/rts/node_modules/
-          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
-          restore-keys: |
-            ${{ github.run_id }}-${{ github.job }}
+      # - name: Restore the previous bundle
+      #   uses: actions/cache@v2
+      #   with:
+      #     path: |
+      #       app/rts/node_modules/
+      #     key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+      #     restore-keys: |
+      #       ${{ github.run_id }}-${{ github.job }}
 
       # Tar the bundles to speed up the upload & download process
       - name: Tar the rts bundles
