Cleaning up to remove debug statements

diff --git a/.github/workflows/test-build-docker-image.yml b/.github/workflows/test-build-docker-image.yml
--- a/.github/workflows/test-build-docker-image.yml
+++ b/.github/workflows/test-build-docker-image.yml
@@ -298,9 +298,9 @@ jobs:
   #     - run: echo "::set-output name=run_result::success" > ~/run_result
 
   buildRts:
-    # defaults:
-    #   run:
-    #     working-directory: app/rts
+    defaults:
+      run:
+        working-directory: app/rts
     runs-on: ubuntu-latest
     # Only run this workflow for internally triggered events
     if: |
@@ -320,24 +320,24 @@ jobs:
       - id: timestamp
         run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M:%S')"
 
-      # # In case this is second attempt try restoring status of the prior attempt from cache
-      # - name: Restore the previous run result
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: |
-      #       ~/run_result
-      #     key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
-      #     restore-keys: |
-      #       ${{ github.run_id }}-${{ github.job }}-
+      # In case this is second attempt try restoring status of the prior attempt from cache
+      - name: Restore the previous run result
+        uses: actions/cache@v2
+        with:
+          path: |
+            ~/run_result
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}-
 
-      # # Fetch prior run result
-      # - name: Get the previous run result
-      #   id: run_result
-      #   run: cat ~/run_result 2>/dev/null || echo 'default'
+      # Fetch prior run result
+      - name: Get the previous run result
+        id: run_result
+        run: cat ~/run_result 2>/dev/null || echo 'default'
 
-      # # Incase of prior failure run the job
-      # - if: steps.run_result.outputs.run_result != 'success'
-      #   run: echo "I'm alive!" && exit 0
+      # Incase of prior failure run the job
+      - if: steps.run_result.outputs.run_result != 'success'
+        run: echo "I'm alive!" && exit 0
 
       - name: Use Node.js 16.14.0
         if: steps.run_result.outputs.run_result != 'success'
@@ -365,43 +365,42 @@ jobs:
       - name: Build
         if: steps.run_result.outputs.run_result != 'success'
         run: |
-          echo 'export const VERSION = "${{ steps.vars.outputs.version }}"' > app/rts/src/version.js
-          cd app/rts && ./build.sh
-          ls -l dist
+          echo 'export const VERSION = "${{ steps.vars.outputs.version }}"' > src/version.js
+          yarn build
           ls -l dist/node_modules/@shared/ast
 
       # Restore the previous built bundle if present. If not push the newly built into the cache
-      # - name: Restore the previous bundle
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: |
-      #       app/rts/dist/
-      #     key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
-      #     restore-keys: |
-      #       ${{ github.run_id }}-${{ github.job }}
+      - name: Restore the previous bundle
+        uses: actions/cache@v2
+        with:
+          path: |
+            app/rts/dist/
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
 
       # Restore the previous built bundle if present. If not push the newly built into the cache
-      # - name: Restore the previous bundle
-      #   uses: actions/cache@v2
-      #   with:
-      #     path: |
-      #       app/rts/node_modules/
-      #     key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
-      #     restore-keys: |
-      #       ${{ github.run_id }}-${{ github.job }}
+      - name: Restore the previous bundle
+        uses: actions/cache@v2
+        with:
+          path: |
+            app/rts/node_modules/
+          key: ${{ github.run_id }}-${{ github.job }}-${{ steps.timestamp.outputs.timestamp }}
+          restore-keys: |
+            ${{ github.run_id }}-${{ github.job }}
 
       # Tar the bundles to speed up the upload & download process
       - name: Tar the rts bundles
         run: |
-          ls -al app/rts/dist/node_modules/@shared/ast
-          tar -cvf rts-dist.tar app/rts/dist
+          ls -al dist/node_modules/@shared/ast
+          tar -cvf rts-dist.tar dist
 
       # Upload the build artifact so that it can be used by the test & deploy job in the workflow
       - name: Upload server build bundle
         uses: actions/upload-artifact@v2
         with:
           name: rts-dist
-          path: rts-dist.tar
+          path: app/rts/rts-dist.tar
 
       # - name: Upload RTS dependencies bundle
       #   uses: actions/upload-artifact@v2
@@ -1561,7 +1560,7 @@ jobs:
           ls -l app/rts
           ls -l app/rts/dist/
           echo "**** Going to untar ****"
-          tar -xvf app/rts/dist/rts-dist.tar
+          tar -xvf app/rts/dist/rts-dist.tar -C app/rts/
           echo "Cleaning up the tar files"
           rm app/rts/dist/rts-dist.tar
           echo "**** Directory structure after untar ****"
